/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package finalproject_nerosa_fernancarl;
import javax.swing.JFrame;
/**
 *
 * @author FernanCarl
 */
public class showEditEquipmentDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(showEditEquipmentDialog.class.getName());
    private final EquipmentMainFrame parentFrame;
    private final EquipmentDAO equipmentDAO = new EquipmentDAO();
    private final CategoriesDAO categoriesDAO = new CategoriesDAO();
    private final LocationsDAO locationsDAO = new LocationsDAO();
    
    private final int itemId; // Tracks which physical item we are modifying
    /**
     * Creates new form showEditEquipmentDialog
     */
    public showEditEquipmentDialog(EquipmentMainFrame parent, boolean modal, int itemId, 
                               String currentName, String currentBrand, String currentModel, 
                               String currentCategory, String currentLocation, String currentStatus) {
        super(parent, modal);
        initComponents();
        this.parentFrame = parent;
        this.itemId = itemId;
        loadCategories();
        loadLocations();
        nameField.setText(currentName);
        brandField.setText(currentBrand);
        modelField.setText(currentModel);
        
        setSelectedCategoryByName(currentCategory);
        setSelectedLocationByCode(currentLocation);
        setSelectedStatus(currentStatus); // <--- Process: Automatically select item status row
    }

    // Process: Look up string values across dropdown item arrays to lock active configuration
    private void setSelectedStatus(String statusName) {
        if (statusName == null) return;
        for (int i = 0; i < statusComboBox.getItemCount(); i++) {
            if (statusComboBox.getItemAt(i).toString().equalsIgnoreCase(statusName.trim())) {
                statusComboBox.setSelectedIndex(i);
                break;
            }
        }
    }
    private showEditEquipmentDialog(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
    
    private void loadCategories() {
    categoryComboBox.removeAllItems();

    for (Category c : categoriesDAO.getAllCategories()) {
        categoryComboBox.addItem(c);
    }
}
    
    private void loadLocations() {
    locationComboBox.removeAllItems();
    // FIX: Ensure the variable type matches 'Location'
    for (Location loc : locationsDAO.getAllLocations()) { 
        locationComboBox.addItem(loc);
    }
}
    
    private void setSelectedCategoryByName(String name) {
        for (int i = 0; i < categoryComboBox.getItemCount(); i++) {
            if (categoryComboBox.getItemAt(i).getCategory_name().equalsIgnoreCase(name)) {
                categoryComboBox.setSelectedIndex(i);
                break;
            }
        }
    }

    private void setSelectedLocationByCode(String code) {
        for (int i = 0; i < locationComboBox.getItemCount(); i++) {
            if (locationComboBox.getItemAt(i).getLocation_code().equalsIgnoreCase(code)) {
                locationComboBox.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        brandField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        modelField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        locationComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        btnPanel = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Equipment Details");

        form.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 24, 10, 24));
        form.setLayout(new java.awt.GridLayout(6, 2, 10, 12));

        jLabel1.setText("Name:");
        form.add(jLabel1);
        form.add(nameField);

        jLabel2.setText("Brand:");
        form.add(jLabel2);
        form.add(brandField);

        jLabel3.setText("Model:");
        form.add(jLabel3);
        form.add(modelField);

        jLabel4.setText("Category:");
        form.add(jLabel4);

        form.add(categoryComboBox);

        jLabel5.setText("Location:");
        form.add(jLabel5);

        locationComboBox.addActionListener(this::locationComboBoxActionPerformed);
        form.add(locationComboBox);

        jLabel6.setText("Status:");
        form.add(jLabel6);

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Maintenance", "Borrowed" }));
        statusComboBox.addActionListener(this::statusComboBoxActionPerformed);
        form.add(statusComboBox);

        getContentPane().add(form, java.awt.BorderLayout.CENTER);

        btnPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 14, 10, 14));
        btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);
        btnPanel.add(cancelBtn);

        saveBtn.setBackground(new java.awt.Color(13, 110, 253));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save Changes");
        saveBtn.addActionListener(this::saveBtnActionPerformed);
        btnPanel.add(saveBtn);

        getContentPane().add(btnPanel, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(420, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
    this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
    String updatedName = nameField.getText().trim();
    String updatedBrand = brandField.getText().trim();
    String updatedModel = modelField.getText().trim();
    String updatedStatus = (String) statusComboBox.getSelectedItem(); // <-- Process: Extract user chosen status string
    
    Category selectedCategory = (Category) categoryComboBox.getSelectedItem();
    Location selectedLocation = (Location) locationComboBox.getSelectedItem();

    if (updatedName.isEmpty() || updatedBrand.isEmpty() || updatedModel.isEmpty() || 
        updatedStatus == null || selectedCategory == null || selectedLocation == null) {
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "All fields are required. Please populate all entries.", 
            "Validation Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Process: Execute database modifications via the DAO pipeline
    boolean specUpdated = equipmentDAO.updateEquipmentSpecs(itemId, updatedName, updatedBrand, updatedModel, selectedCategory.getCategory_id());
    
    // FIX: Update your DAO method call to accept the updatedStatus string variable parameter
    boolean itemUpdated = equipmentDAO.updateEquipmentItemDetails(itemId, selectedLocation.getLocation_id(), updatedStatus);

    if (specUpdated && itemUpdated) {
        javax.swing.JOptionPane.showMessageDialog(this, "Equipment updated successfully!");
        
        if (parentFrame != null) {
            parentFrame.refreshTableFromDatabase();
            parentFrame.updateFooterCount();
        }
        this.dispose();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Failed to save database modifications.", 
            "Database Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void locationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationComboBoxActionPerformed

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                showEditEquipmentDialog dialog = new showEditEquipmentDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandField;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<Category> categoryComboBox;
    private javax.swing.JPanel form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<Location> locationComboBox;
    private javax.swing.JTextField modelField;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> statusComboBox;
    // End of variables declaration//GEN-END:variables
}
