/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package finalproject_nerosa_fernancarl;

/**
 *
 * @author FernanCarl
 */
public class showAddEquipmentDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(showAddEquipmentDialog.class.getName());
    private final EquipmentDAO equipmentDAO = new EquipmentDAO();
    private EquipmentMainFrame parentFrame;
    private final CategoriesDAO categoriesDAO = new CategoriesDAO();
    private final LocationsDAO locationsDAO = new LocationsDAO();
    /**
     * Creates new form showAddEquipmentDialog
     */
    public showAddEquipmentDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        if (parent instanceof EquipmentMainFrame) {
        this.parentFrame = (EquipmentMainFrame) parent;
    }
        initComponents();
        loadCategories();
        loadLocations();
    }
    
    private void loadCategories() {
    categoryComboBox.removeAllItems();

    for (Category c : categoriesDAO.getAllCategories()) {
        categoryComboBox.addItem(c);
    }
}
    
    private void loadLocations() {
    locationComboBox.removeAllItems();
    // FIX: Ensure the variable type matches 'Location'
    for (Location loc : locationsDAO.getAllLocations()) { 
        locationComboBox.addItem(loc);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        brandField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        modelField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        locationComboBox = new javax.swing.JComboBox<>();
        btnPanel = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Equipment");

        form.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 24, 10, 24));
        form.setLayout(new java.awt.GridLayout(6, 2, 10, 12));

        jLabel1.setText("Equipment Name:");
        form.add(jLabel1);
        form.add(nameField);

        jLabel2.setText("Brand:");
        form.add(jLabel2);
        form.add(brandField);

        jLabel3.setText("Model:");
        form.add(jLabel3);
        form.add(modelField);

        jLabel4.setText("Category ID:");
        form.add(jLabel4);

        form.add(categoryComboBox);

        jLabel5.setText("Location:");
        form.add(jLabel5);

        form.add(locationComboBox);

        getContentPane().add(form, java.awt.BorderLayout.CENTER);

        btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);
        btnPanel.add(cancelBtn);

        saveBtn.setBackground(new java.awt.Color(13, 110, 253));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);
        btnPanel.add(saveBtn);

        getContentPane().add(btnPanel, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(600, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
    String name = nameField.getText().trim();
String brand = brandField.getText().trim();
String model = modelField.getText().trim();

// 1. Get selections from BOTH combo boxes
Category selectedCategory = (Category) categoryComboBox.getSelectedItem();
Location selectedLocation = (Location) locationComboBox.getSelectedItem(); 

// 2. Validation Checks
if (selectedCategory == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please select a category.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}
if (selectedLocation == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please select an initial location.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}
if (name.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Equipment Name is required.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

// 3. Extract the primary key IDs from your database objects
int categoryId = selectedCategory.getCategory_id();
int locationId = selectedLocation.getLocation_id(); 

// 4. Instantiate the base equipment data record
Equipment eq = new Equipment(0, name, brand, model, categoryId);

// 5. Pass locationId down instead of 'null'
boolean success = equipmentDAO.saveFullEquipmentWithItem(eq, "Available", locationId, null);

// 6. UI Handshake Responses
if (success) {
    javax.swing.JOptionPane.showMessageDialog(this, "Equipment and tracking location saved successfully!");
    this.dispose();
    parentFrame.refreshTableFromDatabase();
    parentFrame.updateFooterCount();
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "Failed to add equipment database records.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                showAddEquipmentDialog dialog = new showAddEquipmentDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandField;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<Category> categoryComboBox;
    private javax.swing.JPanel form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<Location> locationComboBox;
    private javax.swing.JTextField modelField;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
